"""Add attendance start and end time tracking

Revision ID: 89b981c2365b
Revises: 
Create Date: 2025-09-14 22:44:27.967577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b981c2365b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attendance_end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.drop_column('attendance_end_time')
        batch_op.drop_column('attendance_start_time')

    # ### end Alembic commands ###
